---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  retry_on_exit_code:
    - 3
  max_retries: 1

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    attributes:
      apt:
        unattended_upgrades:
          random_sleep: 0
      yum-updatesd:
        run_interval: 600
        updaterefresh: 300
      yum-cron:
        randomwait: 1
        cleanday: 4
        daily:
          random_sleep: 0
        hourly:
          random_sleep: 0
      autoupdates:
        enable: true
        autoreboot:
          enable: true
    run_list:
      - recipe[apt]
      - recipe[cron]
      - recipe[autoupdates]
      - recipe[autoupdates::autoreboot]
  - name: disable
    run_list:
      - recipe[apt]
      - recipe[cron]
      - recipe[autoupdates_test::disable]
